services:
  first:
    build: ./Valuator
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - NATS_URL=nats://nats:4222
      - DB_RUS=db-rus:6379
      - DB_EU=db-eu:6379
      - DB_OTHER=db-other:6379
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:5001
    depends_on:
      - db-rus
      - db-eu
      - db-other
      - nats
  second:
    build: ./Valuator
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - NATS_URL=nats://nats:4222
      - DB_RUS=db-rus:6379
      - DB_EU=db-eu:6379
      - DB_OTHER=db-other:6379
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:5002
    depends_on:
      - db-rus
      - db-eu
      - db-other
      - nats
  db-rus:
    image: "redis:alpine"
  db-eu:
    image: "redis:alpine"
  db-other:
    image: "redis:alpine"
  nginx:
    image: nginx:alpine
    container_name: docker-nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf/nginx.conf://etc/nginx/nginx.conf:ro
    depends_on:
      - first
      - second
  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
  rank-calculator:
    build: ./RankCalculator
    environment:
      - ASPNETCORE_URLS=http://+:5010
      - NATS_URL=nats://nats:4222
      - DB_RUS=db-rus:6379
      - DB_EU=db-eu:6379
      - DB_OTHER=db-other:6379
    ports:
      - 5010:5010
    depends_on: 
      - nats
      - db-rus
      - db-eu
      - db-other
  event-logger-rank:
    environment:
      - NATS_URL=nats://nats:4222
    build:
      context: .
      dockerfile: EventLogger/Dockerfile
    command: ["Rank", "rank.calculated"]
    depends_on:
      - nats
  event-logger-similarity:
    environment:
      - NATS_URL=nats://nats:4222
    build:
      context: .
      dockerfile: EventLogger/Dockerfile
    command: ["Similarity", "similarity.calculated"]
    depends_on:
      - nats
