services: 
  first:
    build: .
    environment:
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - 5001:5001
    depends_on:
      - redis
    networks:
      - docker-network
  second:
    build: .
    environment:
      - ASPNETCORE_URLS=http://+:5002
    ports:
      - 5002:5002
    depends_on:
      - redis
    networks:
      - docker-network
  redis:
    image: "redis:alpine"
    networks:
      - docker-network
  nginx:
    image: nginx:alpine
    container_name: docker-nginx
    ports:
      - 8080:8080
    volumes:
      - ./../nginx/conf/nginx.conf://etc/nginx/nginx.conf:ro
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge